// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeezblhwzkwrxeomppjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZXpibGh3emt3cnhlb21wcGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTM0NzcsImV4cCI6MjA3NDEyOTQ3N30.F28z2AXYZ7rUh5XKkcGRIZyEeGifZUDcuk7_3c_ydok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});